# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess_tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('is_avaliable', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
