# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0003_auto_20160706_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess',
            name='elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chess',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chess',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chess_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
