# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0005_auto_20160707_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='EndTime',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='round',
            name='History',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='round',
            name='StartTime',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
