# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0007_auto_20160707_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_round',
            name='round_id',
        ),
        migrations.RemoveField(
            model_name='tour_round',
            name='tour_id',
        ),
        migrations.AddField(
            model_name='round',
            name='tour',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='chess_tournament.Tournament'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tour_Round',
        ),
    ]
