# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0009_auto_20160707_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
