# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0010_auto_20160708_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='roundTmeLimit',
            new_name='roundTimeLimit',
        ),
        migrations.AddField(
            model_name='round',
            name='player_1_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='player_1_time_left',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='round',
            name='player_2_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='player_2_time_left',
            field=models.IntegerField(default=-1),
        ),
    ]
