# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0011_auto_20160710_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='player_1_connected',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player_1_time_left',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player_2_connected',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player_2_time_left',
        ),
        migrations.AddField(
            model_name='chess',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chess',
            name='round_time_left',
            field=models.IntegerField(default=-1),
        ),
    ]
