# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0012_auto_20160710_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='in_progress',
            field=models.IntegerField(default=-1),
        ),
    ]
