# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0014_round_white'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='History',
            new_name='PGN',
        ),
    ]
