# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0015_auto_20160711_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='winnerId',
            field=models.IntegerField(default=-1),
        ),
    ]
