# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0017_round_steptimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='time_player_1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='round',
            name='time_player_2',
            field=models.IntegerField(default=-1),
        ),
    ]
