# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0018_auto_20160711_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='turn',
            field=models.CharField(default='w', max_length=1),
            preserve_default=False,
        ),
    ]
