# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_tournament', '0019_round_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='EndTime',
        ),
        migrations.AddField(
            model_name='round',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
